spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/clinica-flutter/protocol/openid-connect/certs
          issuer-uri: http://localhost/realms/clinica-flutter

  application:
    name: FakeBookStore-API
  datasource:
    password: ''
    username: 'nicola'
    url: jdbc:mysql://localhost:3306/clinicadb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC


server:
  #ssl:
  #key-store-password: password_certificate
  #key-store-type: PKCS12
  #key-store: /home/debian/ssl-cert/certificate.p12
  compression:
    enabled: 'true'
  port: '9000'



keycloack:
  resource: clinica

logging:
  level:
    it:
      frankladder: DEBUG
    org:
      springframework: INFO

debug: false
